# Generated by Django 3.1.6 on 2021-02-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UfoReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('City', models.CharField(max_length=256)),
                ('State', models.CharField(max_length=256)),
                ('Shape', models.CharField(max_length=256)),
                ('Duration', models.CharField(max_length=256)),
                ('Summary', models.CharField(max_length=256)),
                ('Posted', models.DateTimeField()),
            ],
        ),
    ]
