# Generated by Django 3.1.6 on 2021-02-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UFO_Reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_string', models.CharField(max_length=100)),
            ],
        ),
    ]
